services:
  - type: web
    name: pagination-search-api
    runtime: node
    buildCommand: npm install && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
